import type { Metadata } from "next";
import { Fira_Code } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer";
import Navbar from "@/components/navbar";
import LoadingPage from "@/components/Loading";
import MyApp from "@/components/_app";
import CustomCursor from "@/components/custom-cursor";

const fira = Fira_Code({
  variable: "--font-fira-code",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={fira.variable}>
        <CustomCursor />
        <MyApp>{children}</MyApp>
      </body>
    </html>
  );
}
