export const projects = [
  {
    name: "chat-app",
    techStack: ["React", "HTML"],
    img: "https://picsum.photos/id/200/370/315?grayscale",
    description: "this is a chat app where you can chat with your friends",
    url: "https://chat-app.com",
  },
  {
    name: "e-commerce",
    techStack: ["Vue", "HTML"],
    img: "https://picsum.photos/id/270/370/315?grayscale",
    description: "this is an e-commerce app where you can buy things",
    url: "https://e-commerce.com",
  },
  {
    name: "blog",
    techStack: ["Gatsby", "HTML"],
    img: "https://picsum.photos/id/209/370/315?grayscale",
    description: "this is a blog where you can read articles",
    url: "https://blog.com",
  },
  {
    name: "weather-app",
    techStack: ["Angular", "HTML"],
    img: "https://picsum.photos/id/20/370/315?grayscale",
    description: "this is a weather app where you can check the weather",
    url: "https://weather-app.com",
  },
  {
    name: "portfolio",
    techStack: ["Flutter", "HTML"],
    img: "https://picsum.photos/id/29/370/315?grayscale",
    description: "this is a portfolio app where you can showcase your work",
    url: "https://portfolio.com",
  },
  {
    name: "social-media",
    techStack: ["React", "CSS"],
    img: "https://picsum.photos/id/100/370/315?grayscale",
    description: "this is a social media app where you can connect with people",
    url: "https://social-media.com",
  },
  {
    name: "food-delivery",
    techStack: ["Vue", "CSS"],
    img: "https://picsum.photos/id/140/370/315?grayscale",
    description: "this is a food delivery app where you can order food",
    url: "https://food-delivery.com",
  },
  {
    name: "music-player",
    techStack: ["Gatsby", "CSS"],
    img: "https://picsum.photos/id/269/370/315?grayscale",
    description: "this is a music player app where you can listen to music",
    url: "https://music-player.com",
  },
  {
    name: "movie-app",
    techStack: ["Angular", "CSS"],
    img: "https://picsum.photos/id/243/370/315?grayscale",
    description: "this is a movie app where you can watch movies",
    url: "https://movie-app.com",
  },
  {
    name: "todo-app",
    techStack: ["Flutter", "HTML", "CSS"],
    img: "https://picsum.photos/id/40/370/315?grayscale",
    description: "this is a todo app where you can keep track of your tasks",
    url: "https://todo-app.com",
  },
];
